[package]
name = "heartbeat-api"
version = "0.1.0"
edition = "2024"

[dependencies]
heartbeat-core = { path = "../heartbeat-core" }
axum = "0.8"
tokio.workspace = true
tower-http = { version = "0.6", features = ["trace", "timeout"] }
tracing.workspace = true
tracing-subscriber.workspace = true
