[package]
name = "heartbeat-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
heartbeat-core = { path = "../heartbeat-core" }
lambda_runtime = "1"
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
